from fastapi.testclient import TestClient
from network_device_api.main import app
import pytest, os, json

client = TestClient(app)

@pytest.mark.scrapli_replay
def test_show_vlans():
    """Test device in SDA lab"""
    response = client.get("/10.2.32.33/vlans")
    assert response.json() == {    
            "message": "Command executed sucessfully",
            "detail": {'vlans': {'1': {'interfaces': ['TwentyFiveGigE1/0/2',
                                           'TwentyFiveGigE1/0/4',
                                           'TwentyFiveGigE1/0/5',
                                           'TwentyFiveGigE1/0/6',
                                           'TwentyFiveGigE1/0/7',
                                           'TwentyFiveGigE1/0/8',
                                           'TwentyFiveGigE1/0/10',
                                           'TwentyFiveGigE1/0/11',
                                           'TwentyFiveGigE1/0/12',
                                           'TwentyFiveGigE1/0/13',
                                           'TwentyFiveGigE1/0/14',
                                           'TwentyFiveGigE1/0/15',
                                           'TwentyFiveGigE1/0/16',
                                           'TwentyFiveGigE1/0/17',
                                           'TwentyFiveGigE1/0/18',
                                           'TwentyFiveGigE1/0/19',
                                           'TwentyFiveGigE1/0/20',
                                           'TwentyFiveGigE1/0/21',
                                           'TwentyFiveGigE1/0/22',
                                           'TwentyFiveGigE1/0/23',
                                           'TwentyFiveGigE1/0/24',
                                           'HundredGigE1/0/25',
                                           'HundredGigE1/0/26',
                                           'HundredGigE1/0/27',
                                           'HundredGigE1/0/28'],
                            'mtu': 1500,
                            'name': 'default',
                            'said': 100001,
                            'shutdown': False,
                            'state': 'active',
                            'trans1': 0,
                            'trans2': 0,
                            'type': 'enet',
                            'vlan_id': '1'},
                      '100': {'mtu': 1500,
                              'name': 'TempBuild',
                              'said': 100100,
                              'shutdown': False,
                              'state': 'active',
                              'trans1': 0,
                              'trans2': 0,
                              'type': 'enet',
                              'vlan_id': '100'},
                      '1002': {'mtu': 1500,
                               'name': 'fddi-default',
                               'said': 101002,
                               'shutdown': False,
                               'state': 'unsupport',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'fddi',
                               'vlan_id': '1002'},
                      '1003': {'mtu': 1500,
                               'name': 'token-ring-default',
                               'said': 101003,
                               'shutdown': False,
                               'state': 'unsupport',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'tr',
                               'vlan_id': '1003'},
                      '1004': {'mtu': 1500,
                               'name': 'fddinet-default',
                               'said': 101004,
                               'shutdown': False,
                               'state': 'unsupport',
                               'stp': 'ieee',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'fdnet',
                               'vlan_id': '1004'},
                      '1005': {'mtu': 1500,
                               'name': 'trnet-default',
                               'said': 101005,
                               'shutdown': False,
                               'state': 'unsupport',
                               'stp': 'ibm',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'trnet',
                               'vlan_id': '1005'},
                      '3034': {'mtu': 1500,
                               'name': '3034',
                               'said': 103034,
                               'shutdown': False,
                               'state': 'active',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'enet',
                               'vlan_id': '3034'},
                      '3035': {'mtu': 1500,
                               'name': '3035',
                               'said': 103035,
                               'shutdown': False,
                               'state': 'active',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'enet',
                               'vlan_id': '3035'},
                      '3036': {'mtu': 1500,
                               'name': '3036',
                               'said': 103036,
                               'shutdown': False,
                               'state': 'active',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'enet',
                               'vlan_id': '3036'},
                      '3037': {'mtu': 1500,
                               'name': '3037',
                               'said': 103037,
                               'shutdown': False,
                               'state': 'active',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'enet',
                               'vlan_id': '3037'},
                      '3038': {'mtu': 1500,
                               'name': '3038',
                               'said': 103038,
                               'shutdown': False,
                               'state': 'active',
                               'trans1': 0,
                               'trans2': 0,
                               'type': 'enet',
                               'vlan_id': '3038'},
                      '666': {'mtu': 1500,
                              'name': 'VLAN0666',
                              'said': 100666,
                              'shutdown': False,
                              'state': 'active',
                              'trans1': 0,
                              'trans2': 0,
                              'type': 'enet',
                              'vlan_id': '666'}}},
        }

@pytest.mark.scrapli_replay
def test_show_vlan():
    """Test device in SDA lab"""
    response = client.get("/10.2.32.33/vlans/?vlan_id=666")
    assert response.json() == {
        "message": "Command executed sucessfully",
        "detail": {'brdg-mode': '-',
                    'bridge-no': '-',
                    'mtu': '1500',
                    'parent': '-',
                    'ports': ['Twe1/0/1', 'Twe1/0/3', 'Twe1/0/9'],
                    'ring-no': '-',
                    'said': '100666',
                    'status': 'active',
                    'stp': '-',
                    'trans1': '0',
                    'trans2': '0',
                    'type': 'enet',
                    'vlan-id': 666,
                    'vlan-name': 'VLAN0666'},
    }

@pytest.mark.scrapli_replay
def test_show_ip_int_brief():
    response = client.get("/10.2.32.33/ip-interfaces/")
    assert response.json() == {
        "message": "Command executed sucessfully",
        "detail": {'interface': {'GigabitEthernet0/0': {'interface_is_ok': 'YES',
                                                 'ip_address': 'unassigned',
                                                 'method': 'unset',
                                                 'protocol': 'down',
                                                 'status': 'down'},
                          'HundredGigE1/0/25': {'interface_is_ok': 'YES',
                                                'ip_address': 'unassigned',
                                                'method': 'unset',
                                                'protocol': 'down',
                                                'status': 'down'},
                          'HundredGigE1/0/26': {'interface_is_ok': 'YES',
                                                'ip_address': 'unassigned',
                                                'method': 'unset',
                                                'protocol': 'down',
                                                'status': 'down'},
                          'HundredGigE1/0/27': {'interface_is_ok': 'YES',
                                                'ip_address': 'unassigned',
                                                'method': 'unset',
                                                'protocol': 'down',
                                                'status': 'down'},
                          'HundredGigE1/0/28': {'interface_is_ok': 'YES',
                                                'ip_address': 'unassigned',
                                                'method': 'unset',
                                                'protocol': 'down',
                                                'status': 'down'},
                          'LISP0': {'interface_is_ok': 'YES',
                                    'ip_address': 'unassigned',
                                    'method': 'unset',
                                    'protocol': 'up',
                                    'status': 'up'},
                          'LISP0.4097': {'interface_is_ok': 'YES',
                                         'ip_address': '10.2.33.65',
                                         'method': 'unset',
                                         'protocol': 'up',
                                         'status': 'up'},
                          'LISP0.4099': {'interface_is_ok': 'YES',
                                         'ip_address': '10.43.26.5',
                                         'method': 'unset',
                                         'protocol': 'up',
                                         'status': 'up'},
                          'LISP0.4102': {'interface_is_ok': 'YES',
                                         'ip_address': '10.43.26.9',
                                         'method': 'unset',
                                         'protocol': 'up',
                                         'status': 'up'},
                          'LISP0.4106': {'interface_is_ok': 'YES',
                                         'ip_address': '10.43.26.17',
                                         'method': 'unset',
                                         'protocol': 'up',
                                         'status': 'up'},
                          'LISP0.4107': {'interface_is_ok': 'YES',
                                         'ip_address': '10.43.26.1',
                                         'method': 'unset',
                                         'protocol': 'up',
                                         'status': 'up'},
                          'Loopback0': {'interface_is_ok': 'YES',
                                        'ip_address': '10.2.32.33',
                                        'method': 'manual',
                                        'protocol': 'up',
                                        'status': 'up'},
                          'Loopback1021': {'interface_is_ok': 'YES',
                                           'ip_address': '10.43.16.1',
                                           'method': 'manual',
                                           'protocol': 'up',
                                           'status': 'up'},
                          'Loopback1022': {'interface_is_ok': 'YES',
                                           'ip_address': '10.43.0.1',
                                           'method': 'manual',
                                           'protocol': 'up',
                                           'status': 'up'},
                          'Loopback60000': {'interface_is_ok': 'YES',
                                            'ip_address': '10.2.33.65',
                                            'method': 'manual',
                                            'protocol': 'up',
                                            'status': 'up'},
                          'Tunnel0': {'interface_is_ok': 'YES',
                                      'ip_address': '10.2.32.33',
                                      'method': 'unset',
                                      'protocol': 'up',
                                      'status': 'up'},
                          'Tunnel1': {'interface_is_ok': 'YES',
                                      'ip_address': '10.2.33.65',
                                      'method': 'unset',
                                      'protocol': 'up',
                                      'status': 'up'},
                          'TwentyFiveGigE1/0/1': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                          'TwentyFiveGigE1/0/10': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/11': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/12': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/13': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/14': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/15': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/16': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/17': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/18': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/19': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/2': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                          'TwentyFiveGigE1/0/20': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/21': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/22': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/23': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/24': {'interface_is_ok': 'YES',
                                                   'ip_address': 'unassigned',
                                                   'method': 'unset',
                                                   'protocol': 'down',
                                                   'status': 'down'},
                          'TwentyFiveGigE1/0/3': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                          'TwentyFiveGigE1/0/4': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                          'TwentyFiveGigE1/0/5': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                          'TwentyFiveGigE1/0/6': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                          'TwentyFiveGigE1/0/7': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                          'TwentyFiveGigE1/0/8': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'down',
                                                  'status': 'down'},
                          'TwentyFiveGigE1/0/9': {'interface_is_ok': 'YES',
                                                  'ip_address': 'unassigned',
                                                  'method': 'unset',
                                                  'protocol': 'up',
                                                  'status': 'up'},
                          'Vlan1': {'interface_is_ok': 'YES',
                                    'ip_address': 'unassigned',
                                    'method': 'manual',
                                    'protocol': 'up',
                                    'status': 'up'},
                          'Vlan100': {'interface_is_ok': 'YES',
                                      'ip_address': '192.168.100.2',
                                      'method': 'manual',
                                      'protocol': 'up',
                                      'status': 'up'},
                          'Vlan3034': {'interface_is_ok': 'YES',
                                       'ip_address': '10.43.26.1',
                                       'method': 'manual',
                                       'protocol': 'up',
                                       'status': 'up'},
                          'Vlan3035': {'interface_is_ok': 'YES',
                                       'ip_address': '10.43.26.5',
                                       'method': 'manual',
                                       'protocol': 'up',
                                       'status': 'up'},
                          'Vlan3036': {'interface_is_ok': 'YES',
                                       'ip_address': '10.43.26.9',
                                       'method': 'manual',
                                       'protocol': 'up',
                                       'status': 'up'},
                          'Vlan3037': {'interface_is_ok': 'YES',
                                       'ip_address': '10.43.26.13',
                                       'method': 'manual',
                                       'protocol': 'up',
                                       'status': 'up'},
                          'Vlan3038': {'interface_is_ok': 'YES',
                                       'ip_address': '10.43.26.17',
                                       'method': 'manual',
                                       'protocol': 'up',
                                       'status': 'up'},
                          'Vlan666': {'interface_is_ok': 'YES',
                                      'ip_address': '10.2.34.2',
                                      'method': 'manual',
                                      'protocol': 'up',
                                      'status': 'up'}}}
    }

@pytest.mark.scrapli_replay
def test_show_interfaces():
    path = "tests/device_outputs/show_interfaces.json"
    response = client.get("/10.2.32.33/interfaces/")
    if not os.path.exists(path):
        with open(path, 'w') as f:
            f.write(json.dumps(response.json()))

    with open(path) as f:
        show_interfaces = json.load(f)

    assert response.json() == show_interfaces

@pytest.mark.scrapli_replay
def test_show_interface():
    response = client.get("/10.2.32.33/interfaces/?interface_name=loopback0")
    assert response.json() == {
        "message": "Command executed sucessfully",
        'detail': {'Loopback0': {'bandwidth': 8000000,
                          'counters': {'in_abort': 0,
                                       'in_broadcast_pkts': 0,
                                       'in_crc_errors': 0,
                                       'in_errors': 0,
                                       'in_frame': 0,
                                       'in_giants': 0,
                                       'in_ignored': 0,
                                       'in_multicast_pkts': 0,
                                       'in_no_buffer': 0,
                                       'in_octets': 0,
                                       'in_overrun': 0,
                                       'in_pkts': 0,
                                       'in_runts': 0,
                                       'in_throttles': 0,
                                       'last_clear': 'never',
                                       'out_broadcast_pkts': 0,
                                       'out_buffer_failure': 0,
                                       'out_buffers_swapped': 0,
                                       'out_collision': 0,
                                       'out_errors': 0,
                                       'out_interface_resets': 0,
                                       'out_multicast_pkts': 0,
                                       'out_octets': 45350149,
                                       'out_pkts': 1126739,
                                       'out_underruns': 0,
                                       'out_unknown_protocl_drops': 248555,
                                       'rate': {'in_rate': 0,
                                                'in_rate_pkts': 0,
                                                'load_interval': 300,
                                                'out_rate': 0,
                                                'out_rate_pkts': 0}},
                          'delay': 5000,
                          'description': 'Fabric Node Router ID',
                          'enabled': True,
                          'encapsulations': {'encapsulation': 'loopback'},
                          'ipv4': {'10.2.32.33/32': {'ip': '10.2.32.33',
                                                     'prefix_length': '32'}},
                          'is_deleted': False,
                          'keepalive': 10,
                          'last_input': '00:00:04',
                          'last_output': '00:00:13',
                          'line_protocol': 'up',
                          'mtu': 1514,
                          'oper_status': 'up',
                          'output_hang': 'never',
                          'port_channel': {'port_channel_member': False},
                          'queues': {'input_queue_drops': 0,
                                     'input_queue_flushes': 0,
                                     'input_queue_max': 75,
                                     'input_queue_size': 0,
                                     'output_queue_max': 0,
                                     'output_queue_size': 0,
                                     'queue_strategy': 'fifo',
                                     'total_output_drop': 0},
                          'reliability': '255/255',
                          'rxload': '1/255',
                          'txload': '1/255',
                          'type': 'Loopback'}},
    }

@pytest.mark.scrapli_replay
def test_configure_interface():
    payload = {
        'name': 'gi0/0', 
        'description': 'testint', 
        'enabled': False
        }
    response = client.post("/10.2.32.33/interfaces/", json=payload)
    assert response.json() == {
        "message": "Config changed sucessfully"
    }

    response = client.get("/10.2.32.33/interfaces/?interface_name=gi0/0")
    assert response.json()['detail']['GigabitEthernet0/0']['enabled'] == False
    assert response.json()['detail']['GigabitEthernet0/0']['description'] == 'testint'
 


@pytest.mark.scrapli_replay
def test_show_run_interfaces():
    response = client.get("/10.2.32.33/interfaces-config/?interface_name=gi0/0")

    assert response.json() == {
        'message': 'Command executed sucessfully',
        'detail': {
            'interfaces': {
                'GigabitEthernet0/0': {
                    'negotiation_auto': True,
                    'shutdown': True,
                    'vrf': 'Mgmt-vrf'
                    }}},
        }